### ISSUE TITLE
Please fix doctests

### ISSUE THREAD

**Issue by iiYese** [laundmo/bevy_screen_diagnostics#5]
Had a go at bumping the plugin for bevy `0.11`. Was fairly trivial with the migration guide. I spent a lot more time trying to update the examples and docs before I gave up. Not maintaining the tests or having docs that fail make it harder for people to make simple contributions like this. Hiding code in doc examples can be done with a `# ` preceding what you want to hide but this should still be used sparingly.

**Comment by laundmo** [comment]
fixed doctests in https://github.com/laundmo/bevy_screen_diagnostics/commit/013d3314ee658967b2411bb824dd0a20008b253a

while this was clearly my mistake, was the accusing tone neccessary?

i'll see about updating to 0.11 myself now.

**Comment by iiYese** [comment]
Didn't think I came off that way when writing it. Apologies if I did and I would appreciate being told what specifically people might take issue with. In any case Thank You!
